name: Release
on:
  release:
    types: [published]
jobs:
  Build:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: docker.pkg.github.com
      IMAGE: semantic-release
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --tag localbuild/image:latest
    - name: Docker Login 
      run: docker login $REGISTRY -u ${GITHUB_ACTOR} -p ${GITHUB_TOKEN}
    - name: Docker Tag Release
      run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF#refs/tags/}
    - name: Docker Push Release
      run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF#refs/tags/}
    - name: Docker Tag Latest
      run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest
    - name: Docker Push Latest
      run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest

