name: Build
on:
  push:
    branches:
      - 'master'
jobs:
  Build:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: docker.pkg.github.com
      IMAGE: semantic-release
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --tag localbuild/image:latest
    - name: Check Version
      run: export VERSION="v$(npx semantic-release | grep "The next release version is" | sed -ne 's/.*The\ next\ release\ version\ is\ \([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')"
    - name: Echo Version
      run: echo $VERSION
      # - name: Docker Login 
    #   run: docker login docker.pkg.github.com -u ci -p ${GITHUB_TOKEN}
    # - name: Docker Tag Branch
    #   run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF##*/}
    # - name: Docker Push Branch
    #   run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF##*/}
    # - name: Docker Tag Release
    #   run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$VERSION
    # - name: Docker Push Release
    #   run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$VERSION
    # - name: Docker Tag Latest
    #   run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest
    # - name: Docker Push Latest
    #   run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest

