name: Release
on: 
    push:
        tags:
jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      IMAGE: docker.pkg.github.com/caos/semantic-release/semantic-release
    steps:
    - name: Source checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      shell: bash
      run: docker build --tag ${IMAGE}:latest --file ./Dockerfile .
    - uses: anchore/scan-action@master
      with:
        image-reference: "docker.pkg.github.com/caos/semantic-release/semantic-release:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: true
        include-app-packages: true
    - name: Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export GIT_TAG="v$(npx semantic-release --dry-run --plugins=@semantic-release/commit-analyzer --analize-commits | grep "The next release version is" | sed -ne 's/.*The\ next\ release\ version\ is\ \([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')"
        [[ "$GIT_TAG" == "v" ]] && echo "Exiting, as no new version needs to be released" && exit 0
        export TAG_VERSION=${IMAGE}:${GIT_TAG}
        docker login docker.pkg.github.com -u ci -p ${GITHUB_TOKEN}
        docker tag ${TAG_LATEST} ${TAG_VERSION}
        docker push ${TAG_LATEST}
        docker push ${TAG_VERSION}

        npx semantic-release