name: Build
on:
  push:
    branches:
      - 'dev/*'
      - 'master'
jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: docker.pkg.github.com
      IMAGE: semantic-release
    steps: 
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag $REGISTRY/$GITHUB_REPOSITORY/$ARTIFACT:$GITHUB_REF
    - name: Docker Push
      run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$GITHUB_REF
    - name: Check Version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release