name: Build
on:
  push:
    branches:
      - '*'
jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: docker.pkg.github.com
      IMAGE: semantic-release
    steps: 
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Docker Build
      run: docker build . --tag $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$BRANCH
    - name: Docker Push
      if: github.ref == 'master'
      run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$GITHUB_REF
    #- name: Check Version
    #  run: npx semantic-release